"""Regenerate registry/repos.generated.yaml from live GitHub metadata.

    uv run fleet sync-registry

Enumerates every repository the authenticated user can reach (owned, via org
membership, or as a collaborator) and keeps the ones belonging to an owner
listed in registry/owners.txt, in that file's order. Add an org to owners.txt
and its repos appear on the next sync; nothing else is hardcoded.

EVERY `gh` ACCOUNT IS ASKED, not just the active one. A machine with two logins
reaches two disjoint sets of repositories, and `user/repos` answers only for
the active account, so one pass wrote a map silently missing every owner the
other logins reach, with the same `no accessible repos` warning a typo gives.
Tokens are read BY NAME and never by switching; scripts/lib/gh_accounts.py is
the seam and argues the mechanism.

One account that cannot be listed is NAMED and costs only its own repos. EVERY
account failing is no answer at all (an offline laptop, an outage, SSO lapsed
everywhere), and the map is then left exactly as it was rather than overwritten
with an empty one.

The file is GENERATED, so never hand-edit it, and gitignored like
registry/owners.txt; .gitignore says why. Curated context lives in
registry/context/<repo>.md, which this never touches. Requires `gh`,
authenticated; no PAT and no CI secret.
"""

from __future__ import annotations

import importlib.util
import json
import os
import shutil
import sys

LIB = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(os.path.dirname(LIB))
OWNERS_FILE = os.path.join(REPO_ROOT, "registry", "owners.txt")
OUT = os.path.join(REPO_ROOT, "registry", "repos.generated.yaml")
ENDPOINT = "user/repos?per_page=100&affiliation=owner,collaborator,organization_member"


def _load_sibling(name: str, filename: str):
    """A module beside this file, keyed in sys.modules as every loader keys it."""
    if name in sys.modules:
        return sys.modules[name]
    spec = importlib.util.spec_from_file_location(name, os.path.join(LIB, filename))
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


gh = _load_sibling("fleet_gh_accounts", "gh_accounts.py")
platform = _load_sibling("fleet_platform", "fleet_platform.py")


def fail(message: str) -> int:
    sys.stderr.write(f"error: {message}\n")
    return 1


def read_owners(path: str) -> list[str]:
    """One owner per line; `#` starts a comment, blank lines are ignored."""
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    return [word for line in lines if (word := "".join(line.split("#", 1)[0].split()))]


def map_host() -> str:
    """GitHub, unless `GH_HOST` says otherwise: the variable `gh api` itself obeys,
    so enumerating logins for any other host would name tokens it never uses."""
    return os.environ.get("GH_HOST") or "github.com"


def listing(token: str) -> list[dict] | None:
    """Every repository one account reaches, or None when it could not be listed."""
    done = gh.api_as(token, "--paginate", ENDPOINT, "--jq", ".[]")
    sys.stderr.write(done.stderr)
    if done.returncode != 0:
        return None
    try:
        return [json.loads(line) for line in done.stdout.splitlines() if line.strip()]
    except ValueError:
        return None


def merged(repos: list[dict]) -> list[dict]:
    """One entry per `full_name`, newest push first.

    A repository two accounts both reach is ONE repository, or it would double
    every count. The order is jq's `unique_by(.full_name) | sort_by(.pushed_at)
    | reverse`, so a map regenerated by either implementation reads the same.
    """
    first: dict[str, dict] = {}
    for repo in repos:
        first.setdefault(str(repo.get("full_name")), repo)
    out = sorted(first.values(), key=lambda r: str(r.get("full_name")))
    out.sort(key=lambda r: (r.get("pushed_at") is not None, str(r.get("pushed_at") or "")))
    out.reverse()
    return out


def scalar(value) -> str:
    """How jq's string interpolation prints a value."""
    return value if isinstance(value, str) else json.dumps(value)


def quoted(value, default: str) -> str:
    """jq's `(value // default) | @json`."""
    return json.dumps(default if value is None or value is False else value, ensure_ascii=False)


def entry(repo: dict) -> str:
    topics = repo.get("topics") or []
    return (
        f"    - name: {scalar(repo.get('name'))}\n"
        f"      url: {scalar(repo.get('html_url'))}\n"
        f"      visibility: {'private' if repo.get('private') else 'public'}\n"
        f"      role: {quoted(repo.get('role_name'), '-')}\n"
        f"      archived: {scalar(repo.get('archived'))}\n"
        f"      fork: {scalar(repo.get('fork'))}\n"
        f"      language: {quoted(repo.get('language'), '-')}\n"
        f"      default_branch: {quoted(repo.get('default_branch'), '-')}\n"
        f"      pushed_at: {scalar(repo.get('pushed_at'))}\n"
        f"      topics: [{', '.join(str(t) for t in topics)}]\n"
        f"      description: {quoted(repo.get('description'), '')}\n"
    )


def sync() -> int:
    if not shutil.which("gh"):
        return fail("gh not found")
    if not os.path.isfile(OWNERS_FILE):
        return fail(f"missing {OWNERS_FILE} — it is yours and gitignored.\n"
                    "       Copy the tracked example and fill it in:\n"
                    "         cp registry/owners.example.txt registry/owners.txt")
    owners = read_owners(OWNERS_FILE)
    if not owners:
        return fail(f"no owners configured. Edit {OWNERS_FILE} and uncomment (or add) your\n"
                    "       GitHub username and any orgs you belong to, one per line.")

    host = map_host()
    accounts = gh.accounts(host)
    sys.stderr.write("fetching every accessible repository ...\n")

    repos: list[dict] = []
    if not accounts:
        # The documented fallback, not a failure: the active session alone.
        one = listing("")
        if one is None:
            return fail(f"could not list repositories with the active gh session.\n"
                        f"       {OUT} is left exactly as it was.")
        repos = one
    else:
        listed = 0
        for login in accounts:
            token = gh.account_token(host, login)
            if not token:
                sys.stderr.write(f"warning: no usable token for gh account '{login}' — "
                                 "its repositories are not in this map\n")
                continue
            one = listing(token)
            if one is None:
                sys.stderr.write(f"warning: could not list repositories for gh account '{login}' — "
                                 "its repositories are not in this map\n")
                continue
            listed += 1
            repos.extend(one)
        if listed == 0:
            return fail(f"not one of the {len(accounts)} gh accounts above could be listed.\n"
                        f"       {OUT} is left exactly as it was rather than\n"
                        "       overwritten with an empty map.")

    everything = merged(repos)

    def owner_of(repo: dict):
        return (repo.get("owner") or {}).get("login")

    wanted = set(owners)
    total = sum(1 for r in everything if owner_of(r) in wanted)

    text = (
        "# GENERATED by `uv run fleet sync-registry` — do not edit by hand.\n"
        "# Every accessible repository under the owners in registry/owners.txt.\n"
        "# Curated context lives in registry/context/<repo>.md.\n"
        "# Regenerate: uv run fleet sync-registry\n"
        + ("owners: []\n" if total == 0 else "owners:\n")
    )
    for owner in owners:
        mine = [r for r in everything if owner_of(r) == owner]
        if not mine:
            sys.stderr.write(f"warning: no accessible repos for owner '{owner}'\n")
            continue
        text += f"  - name: {owner}\n    repo_count: {len(mine)}\n    repos:\n"
        text += "".join(entry(r) for r in mine)

    emitted = len({owner_of(r) for r in everything} & wanted)
    text += f"totals:\n  repos: {total}\n  owners: {emitted}\n"

    platform.write_record(OUT, text)
    sys.stderr.write(f"wrote {OUT} ({total} repos across {emitted} owners)\n")
    return 0


def main(argv: list[str]) -> int:
    if argv[:1] in (["-h"], ["--help"]):
        sys.stdout.write(__doc__)
        return 0
    if argv:
        sys.stderr.write("usage: fleet sync-registry\n")
        return 2
    return sync()


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
